### ISSUE TITLE
Support image with link

### ISSUE THREAD

**Issue by breiko83** [stormz/kramdown-prismic#1]
Hello - thanks for the amazing work!
Do you think you will support images with a link in the future? 

```
<a href="https://www.google.com"><img src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png" alt="Google Logo"></a>
```

to

```
{
  "type": "image",
  "content": { "text": "", "spans": [] },
  "data": {
    "origin": {
      "url": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png"
    },
    "alt": "Google Logo",
    "linkTo": {
      "url": "https://www.google.com",
      "preview": {
        "title": "https://www.google.com"
      }
    }
  }
}
```

**Comment by francois2metz** [comment]
@breiko83 That should be doable.  I can take a look later.

**Comment by francois2metz** [comment]
@breiko83 Do you have any documentation on images with a link ? I saw https://prismic.io/docs/core-concepts/import-json-reference#paragraph-with-an-inline-link-to-a-media-library-item but it's not the same as yours.

**Comment by francois2metz** [comment]
Hi, I have added support of links with only an image inside in the version **0.2.2**.
