### ISSUE TITLE
Targets for hyperlink tags

### ISSUE THREAD

**Issue by sendmenas** [stormz/kramdown-prismic#11]
Hi again,
Thank you for your work and such a fast response last time. I am still working on my migration project and noticed one more thing. I don't think this is an error, but rather a missing feature maybe 😄 when converting hyperlink tags the target is ignored. Would it be possible to add this info as well?
What I get after parsing
```
"spans": [
  {
    "start": 11,
    "end": 26,
    "type": "hyperlink",
    "data": {
      "url": "https://link.com"
    }
  }
]
```
What I would like to get
```
"spans": [
  {
    "start": 11,
    "end": 26,
    "type": "hyperlink",
    "data": {
      "url": "https://link.com",
      "target": "_blank"
    }
  }
]
```
I noticed this with inline hyperlink, that are in paragraph, so not sure how it acts with stand alone hyperlink.

**Comment by francois2metz** [comment]
Hi @sendmenas. Thanks for reporting this. I cannot find any documentation on the target attribute. Where did you find it?

**Comment by sendmenas** [comment]
@francois2metz not sure about that 😄 but this is what I get when exporting documents from prismic with target blank
