### ISSUE TITLE
Video embed URL does not translate because it's hard-coded.

### ISSUE THREAD

**Issue by tjkohli** [stormz/kramdown-prismic#12]
Can someone please point me in the right direction how this should output the proper URL instead a hard-coded one?

https://github.com/stormz/kramdown-prismic/blob/3c06637612baa3ec2f772f23d3d175b0f7a25202/lib/kramdown/converter/prismic.rb#L182

**Comment by francois2metz** [comment]
Oops. It seems that I forgot to remove it!
