### ISSUE TITLE
<a> tag inside <span> tag are rendered as plain text

### ISSUE THREAD

**Issue by patzsy** [stormz/kramdown-prismic#15]
Hi guys,
I have an issue when parsing from html to prismic format.
For example my html text:

```
<p>
    <span style="font-weight: 400;">this is some text1 <a href="https://link1.com/">link text 1</a> with link inside</span>
    <a href="https://link2.com/"><span style="font-weight: 400;">this is some text2 </span></a><span style="font-weight: 
     400;">with link inside.</span>
</p>
```

The output is like this:
```
[
  {
    type: 'paragraph',
    content: { 
      text: 'this is some text1 link text 1 with link inside.this is some text2 link text 2 with link inside'
    }, 
    spans: [
            {
              "type": "hyperlink",
              "data": {
                "url": "https://link2.com/"
              },
              "start": x,
              "end": x
            }
          ]
    }
]
```

Basically, the href tag for link1.com will be missing and only shows for link2.com. Is this because the link1.com is wrapped inside a span tag and nested inside p tag?
Any help would be greatly appreciated, thanks!

**Comment by francois2metz** [comment]
Hi there, converting span elements is not supported. You should always lookup for warnings, see https://github.com/stormz/kramdown-prismic#lookup-for-warnings
