### ISSUE TITLE
Add support for <strong> tags

### ISSUE THREAD

**Issue by skilar** [stormz/kramdown-prismic#6]
I found an error similar to #5, but this time when importing HTML with a `<strong>` tag. Kramdown-prismic throws the error: `undefined method 'convert_strong'`. Sorry for not catching this one when reporting the previous!

**Comment by francois2metz** [comment]
Hi @skilar! Thanks for the report. I added support of `strong` and `em` elements when parsing HTML documents. 
Keep going posting issues when you see them, I'm happy to fix them.
I have released the version 0.3.4.

**Comment by skilar** [comment]
Thanks again, @francois2metz! I haven't run into any more issues, but if I do I'll be sure to post them.
