### ISSUE TITLE
Support for <br /> html tag

### ISSUE THREAD

**Issue by simsComputing** [stormz/kramdown-prismic#7]
Hello,

I am encountering the following error : `convert_element': undefined method `convert_br' while exporting some wordpress content. 

Would it be possible for you to add support for this br tag please ?

Thank you very much,
Simon

**Comment by francois2metz** [comment]
Hi there. Thanks for reporting this issue. I have fixed it on the 0.3.5 version of the gem.

**Comment by simsComputing** [comment]
Hi @francois2metz , thank you so much for your reactivity. I needed that :) 

Have a good day
