### ISSUE TITLE
Support for nested list (ex: <ol> in <li>)

### ISSUE THREAD

**Issue by YohannMateo** [stormz/kramdown-prismic#8]
Hello,

I am encountering the following error : `block in extract_content': undefined method `extract_span_ol' while exporting some wordpress content.

Would it be possible for you to add support for nested list please ?

Thank you very much,
Yohann

**Comment by francois2metz** [comment]
Hi @YohannMateo. Thanks for reporting the issue. I totally missed the numbered list case previously. I have released the `0.3.6` version that fix it.

**Comment by YohannMateo** [comment]
Hi,
Good news, thank you :D
