### ISSUE TITLE
Support for header in list

### ISSUE THREAD

**Issue by jonathan-lauvernier** [stormz/kramdown-prismic#9]
Hello,

First thank you for this awesome library and for your reactivity to fix issues !

I am encountering the following error : `converter/prismic.rb:230:in `block in extract_content': undefined method `extract_span_header'` while exporting some wordpress content.

code failing : `<ul><li><h4>Title</h4></li></ul>`
version : 0.3.6

Would it be possible for you to add support header in list please ?

Thank you very much,
Jonathan

**Comment by francois2metz** [comment]
Hi Jonathan,

Thanks for reporting this issue. Prismic doesn't support headings in list (It is html valid?), so it'll be extracted outside of the list.
